services:
  - type: web
    name: founderspath-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn server:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
        # Это значение нужно будет добавить вручную в Render Dashboard
        # после деплоя frontend на Vercel
